version: "2"
services:
  candidato:
    build: .
    container_name: candidato    
    environment:
      KEYCLOAK_HOST: keycloak
      CONSUL_HOST: consul
      DB_HOST:
      DB_USER:
      DB_PWD:
    ports:
      - 8082:8082

networks:
  default:
    external:
      name: docker_default
