version: "2"
services:
  candidato:
    build: .
    container_name: candidato    
    environment:
      KEYCLOAK_HOST: keycloak
      CONSUL_HOST: consul
      DB_HOST: postgres
      DB_USER: candidatoapp
      DB_PWD: candidatoapp
    ports:
      - 8082:8082

networks:
  default:
    external:
      name: docker_default
