version: "2"
services:
  gateway-app:
    build: .
    container_name: gateway
    environment:
      KEYCLOAK_HOST: keycloak
      CONSUL_HOST: consul
    
    ports:
      - 8080:8080
networks:
  default:
    external:
      name: docker_default
