version: "2"
services:
  processo-seletivo:
    build: .
    container_name: processo-seletivo    
    environment:
      KEYCLOAK_HOST: keycloak
      CONSUL_HOST: consul
      DB_HOST: postgres
      DB_USER: processoapp
      DB_PWD: processoapp
    ports:
      - 8081:8081

networks:
  default:
    external:
      name: docker_default
