spring:
  application:
    name: processo-seletivo
  datasource:    
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/processo
    username: ${DB_USER:processoapp}
    password: ${DB_PWD:processo_pwd}
  jpa:
    repositories.bootstrap-mode: default
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        register-health-check: true
  liquibase:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:9080/auth/realms/edukare/protocol/openid-connect/certs
server:
  port: 8081
