apiVersion: v1
kind: Service
metadata:  
  name: gateway-svc
  namespace: default  
  annotations:
      cloud.google.com/neg: '{"ingress": true}'
spec:  
  selector:
    run: gateway  
  type: ClusterIP
  ports:     
    - port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gateway
  template:
    metadata:
      labels:
        run: gateway
    spec:
      containers:
      - name: gateway
        image: gcr.io/edukare/gateway:1.0.0
        ports:
        - containerPort: 8080
        env:
         - name: CONSUL_HOST
           valueFrom:
             fieldRef:
              fieldPath: status.hostIP
         - name: KEYCLOAK_HOST
           valueFrom:
             configMapKeyRef:
              key: KEYCLOAK_HOST
              name: uris
         - name: KEYCLOAK_PORT
           valueFrom:
             configMapKeyRef:
              key: KEYCLOAK_PORT
              name: uris