apiVersion: v1
kind: Service
metadata:  
  name: webapp-svc
  namespace: default  
spec:  
  selector:
    run: webapp  
  type: LoadBalancer
  ports:
    - port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: webapp
  template:
    metadata:
      labels:
        run: webapp
    spec:
     containers:
       - image: gcr.io/edukare/webapp:latest
         name: webapp
         ports:
           - containerPort: 8080