version: "2"
services:
  escola:
    build: .
    container_name: escola   
    environment:
      KEYCLOAK_HOST: keycloak
      CONSUL_HOST: consul
    ports:
      - 8083:8083

networks:
  default:
    external:
      name: docker_default
