version: '3.4'

services:
  webapp:
    container_name: webapp
    image: webapp   
    build:
      context: .      
    ports:
      - 4200:8080
networks:
  default:
    external:
      name: docker_default
