version: '3'
services:
  consul:
    image: consul:1.9.3
    container_name: consul
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    command: consul agent -dev -ui -client 0.0.0.0
