version: '3'
services:
  keycloak:
    image: jboss/keycloak:12.0.2
    container_name: keycloak
    volumes:
      - ./realm-config/edukare-realm.json:/realm-config/edukare-export.json
    environment:
      - KEYCLOAK_IMPORT=/realm-config/edukare-realm.json
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - 9080:8080
