version: "2"
services:
  keycloak:    
    image: jboss/keycloak:12.0.2
    container_name: keycloak
    command: ['-b',
              '0.0.0.0',
              '-Djboss.socket.binding.port-offset=1000']
    volumes:
      - ./realm-config/edukare-export.1.0.1.json:/realm-config/edukare-export.1.0.1.json
    environment:
      - KEYCLOAK_IMPORT=/realm-config/edukare-export.1.0.1.json
      - KEYCLOAK_USER=
      - KEYCLOAK_PASSWORD=
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=
      - DB_USER=
      - DB_PASSWORD=
    ports:
      - 9080:9080
      - 9443:9443
      - 10990:10990
