version: "2"
services:
  keycloak:    
    image: jboss/keycloak:12.0.2
    container_name: keycloak
    command: ['-b',
              '0.0.0.0',
              '-Djboss.socket.binding.port-offset=1000']
    volumes:
      - ./realm-config/realm-export.json:/realm-config/realm-export.json
    environment:
      - KEYCLOAK_IMPORT=/realm-config/realm-export.json
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - 9080:9080
      - 9443:9443
      - 10990:10990
