version: '3.1'

services:

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER: 
      POSTGRES_DB: 
    volumes:
     - <path/to/storage>:/var/lib/postgresql/data
    ports:
      - 5432:5432